### ISSUE TITLE
link to mothur miseq development data not working 

### ISSUE THREAD

**Issue by cmsmoo** [spholmes/F1000_workflow#10]
The link to the data returns this message:
"The requested URL /MiSeqDevelopmentData/StabilityNoMetaG.tar was not found on this server."

is there another way to get this data to run the workflow? 

Thanks.

**Comment by benjjneb** [comment]
The mothur.org site has been down a lot lately, and it appears this file is currently a casualty. 

Here is a dropbox link that should work for now: https://www.dropbox.com/s/5ue8476y3dzvxx2/StabilityNoMetaG.tar?dl=0

**Comment by padpadpadpad** [comment]
This file downloads fine using 
`download.file("https://www.dropbox.com/s/5ue8476y3dzvxx2/StabilityNoMetaG.tar?dl=0",
                destfile = file.path(miseq_path, "StabilityNoMetaG.tar"))`

 but when unpacking the .tar file it reports:
`Unrecognised archive format`
`Error exit delated from previous errors`
Seems to be a problem with the file downloaded.

Looking at the file in Terminal
`file StabilityNoMetaG.tar`
`HTML document text, ASCII text, with very long lines`

Could the file link provided not be downloading correctly?
Thanks

**Comment by padpadpadpad** [comment]
This works if you manually download the file from the link and do not use the code provided.
Look forward to working through the workflow. 
Cheers
Dan

**Comment by krisrs1128** [comment]
@padpadpadpad I think if you change the end of the link to ?dl=1 then the code should work. The issue is that the file download won't trigger unless dl is set to 1.

**Comment by padpadpadpad** [comment]
Thanks @krisrs1128 will have a go. Are these files also the trimmed versions? As none of them are as long as in the tutorial?

**Comment by krisrs1128** [comment]
Okay, let us know if you have any trouble. Also, remember to delete (or move) the MiSeq_SOP directory before rerunning, otherwise the if() won't evaluate, hadn't thought of that when I wrote earlier.

I'm actually not sure if they're trimmed -- @benjjneb should know though.

**Comment by benjjneb** [comment]
These are the untrimmed/unfiltered fastq files.

Please let us know if this file doesn't or does work for people. I had to recreate the .tar from individual files as I didn't have the original saved.

**Comment by padpadpadpad** [comment]
The downloads works but they are the trimmed files. Here is a file of some of the quality plots. They are already trimmed.

[qual_plot.pdf](https://github.com/spholmes/F1000_workflow/files/608651/qual_plot.pdf)

**Comment by benjjneb** [comment]
Unfortunately it looks like I may not have saved the raw data. I am requesting an update from the mothur team on alternative download locations, and will report back as soon as I hear something.

If anyone happens to have the original .tar file lying around, let me know!

For now, the file I uploaded can be used as is as long as you skip the filtering steps in the workflow.

**Comment by benjjneb** [comment]
The file is once again available from its mothur.org download location, so everything should work as expected again.

**Comment by tahirali-biomics** [comment]
I am trying to download  "MiSeqDevelopmentData"
from http://www.mothur.org, however, the website is currently down. Is there any other place to download this dataset? Thank you.
