### ISSUE TITLE
MIMARKS_Data_combined.csv not created/downloaded

### ISSUE THREAD

**Issue by padpadpadpad** [spholmes/F1000_workflow#12]
The walkthrough states:

"The last bit of information needed is the sample data contained in a .csv file."

But then just sets the path and reads it in and there I cannot find where the file would be created and what information needs to be in it.

Thanks
Dan

**Comment by krisrs1128** [comment]
You're right, this is unclear, the data is in the repository: https://github.com/spholmes/F1000_workflow/tree/master/data

**Comment by krisrs1128** [comment]
We should probably automate the download like we did for the other data.

**Comment by padpadpadpad** [comment]
Especially given the slight difficulty of downloading a single GitHub file. Finally managed it in terminal as:

`wget https://raw.githubusercontent.com/spholmes/F1000_workflow/master/data/MIMARKS_Data_combined.csv`

after changing to the desired directory.
Thanks
Dan

**Comment by joey711** [comment]
I'm not understanding the issue. The expectation is that you would download/clone the whole repository, in which case all the files, including in `data/`, would be available locally, in the (portable) relative path of the scripts you're running.

The entire workflow is completely reproducible as a repository, as-is. 

@spholmes am I missing something?

**Comment by padpadpadpad** [comment]
Ah this is a good point. 

Maybe you should write that in the README.md to make it clearer. I came across this from the [manuscript](https://f1000research.com/articles/5-1492/v2
).

There is no obvious mention of GitHub repository on there and no mention of the desire to clone it. I came by the GitHub repository after I had already started the tutorial analysis.

**Comment by joey711** [comment]
Thanks for clarifying. You may not the only person to miss this.

However, there is a **Data Availability** section toward the end of the manuscript:

## Data availability

Intermediary data for the analyses are made available both on GitHub at https://github.com/spholmes/F1000_workflow 
and at the Stanford digital repository permanent url for this paper: http://purl.stanford.edu/wh250nn9648. 
All other data have been previously published and the links are included in the paper.

Software availability
Bioconductor packages at 
https://www.bioconductor.org/. 
CRAN packages at 
https://cran.r-project.org/.

Permanent repository for the data and program source of this paper: 

https://purl.stanford.edu/wh250nn9648

Latest source code as at the time of publication: 

https://github.com/spholmes/F1000_workflow

Archived source as at the time of publication: 
Zenodo: F1000_workflow: MicrobiomeWorkflowv0.9, doi: 10.5281/zenodo.5454436

Given that this is in the manuscript, I think I will close this issue.
