### ISSUE TITLE
download tar issue

### ISSUE THREAD

**Issue by Brispark** [spholmes/F1000_workflow#7]
I am trying to download the raw data using

> miseq_path <- file.path("data", "MiSeq_SOP")
> file_path <- file.path("data", "filtered")
> 
> if(!file_test("-d", miseq_path)) {
+   dir.create(miseq_path)
+   download.file("http://www.mothur.org/MiSeqDevelopmentData/StabilityNoMetaG.tar",
+                 destfile = file.path(miseq_path, "StabilityNoMetaG.tar"))
+   system(paste0("tar -xvf ", file.path(miseq_path, "StabilityNoMetaG.tar"),
+                 " -C ", miseq_path, "/"))
+ }

but get this error

downloaded 0 bytes

Error in download.file("http://www.mothur.org/MiSeqDevelopmentData/StabilityNoMetaG.tar",  : 
  cannot download all files
In addition: Warning messages:
1: In dir.create(miseq_path) :
  cannot create dir 'data/MiSeq_SOP', reason 'No such file or directory'
2: In download.file("http://www.mothur.org/MiSeqDevelopmentData/StabilityNoMetaG.tar",  :
  URL http://www.mothur.org/MiSeqDevelopmentData/StabilityNoMetaG.tar: cannot open destfile 'data/MiSeq_SOP/StabilityNoMetaG.tar', reason 'No such file or directory'
3: In download.file("http://www.mothur.org/MiSeqDevelopmentData/StabilityNoMetaG.tar",  :
  downloaded length 0 != reported length 884254720

can anyone  guide me as to the cause of the error

**Comment by benjjneb** [comment]
Hi,
Did you set your working directory to the base of the F1000_workflow repository (see the Readme.md)? If you did, when you run `list.files()` the output should look like this:

```
 [1] "data"                "f1000_styles.sty"    "F1000WF.bib"        
 [4] "figure"              "main.rnw"            "PartIdada.rnw"      
 [7] "PartIIIanalysis.rnw" "PartIIphyloseq.rnw"  "README.md"          
[10] "src"                
```
